// <auto-generated />
namespace Primary_School_Management_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ModelWithAnotation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModelWithAnotation));
        
        string IMigrationMetadata.Id
        {
            get { return "201910091741319_ModelWithAnotation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
