// <auto-generated />
namespace UniversityManagementSystemWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class _3512pm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_3512pm));
        
        string IMigrationMetadata.Id
        {
            get { return "201703131113223_3-5-12pm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
