// <auto-generated />
namespace Primary_School_Management_System___2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class StudentAndClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StudentAndClass));
        
        string IMigrationMetadata.Id
        {
            get { return "201910141410365_StudentAndClass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
